const $=(id)=>document.getElementById(id);
function confetti(){for(let i=0;i<120;i++){const c=document.createElement("div");c.className="confetti";c.style.left=Math.random()*100+"vw";c.style.background=["#ff4fb8","#7b2cff","#ffd65a","#48dfff"][Math.floor(Math.random()*4)];c.style.animationDelay=Math.random()*0.45+"s";document.body.appendChild(c);setTimeout(()=>c.remove(),1900)}}
document.querySelectorAll(".tab:not(.soon)").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");$("whoGame").classList.toggle("hidden",btn.dataset.game!=="who");$("shipGame").classList.toggle("hidden",btn.dataset.game!=="ship");$("bingoGame").classList.toggle("hidden",btn.dataset.game!=="bingo")})});

/* QUI SUIS-JE */
let whoSubs=0,whoBlur=18;
function saveWho(){const data={subs:whoSubs,blur:whoBlur,goal:$("whoGoal").value,grid:$("whoGrid").value,answer:$("whoAnswer").value,clue:$("whoClue").textContent,hidden:[...document.querySelectorAll("#whoTiles .tile")].map(t=>t.classList.contains("hidden-tile"))};localStorage.setItem("malou_who",JSON.stringify(data))}
function buildWhoGrid(){const n=parseInt($("whoGrid").value,10);const tiles=$("whoTiles");tiles.style.gridTemplateColumns=`repeat(${n},1fr)`;tiles.style.gridTemplateRows=`repeat(${n},1fr)`;tiles.innerHTML="";for(let i=0;i<n*n;i++){const t=document.createElement("div");t.className="tile";t.textContent="💖";t.addEventListener("click",()=>{if(confirm("Dévoiler cette case manuellement ?")){t.classList.add("hidden-tile");saveWho()}});tiles.appendChild(t)}}
function updateWhoScore(){const goal=parseInt($("whoGoal").value,10)||1;$("whoSubs").textContent=whoSubs;$("whoGoalTxt").textContent=goal;$("whoFill").style.width=Math.min(100,whoSubs/goal*100)+"%";saveWho()}
function revealWhoRandom(){const available=[...document.querySelectorAll("#whoTiles .tile:not(.hidden-tile)")];if(!available.length){$("whoMessage").textContent="🎉 Image totalement dévoilée !";confetti();return}available[Math.floor(Math.random()*available.length)].classList.add("hidden-tile");$("whoMessage").textContent="👀 Une case dévoilée au hasard !";saveWho()}
function lessWhoBlur(silent=false){whoBlur=Math.max(0,whoBlur-1);$("whoImage").style.filter=`blur(${whoBlur}px) saturate(1.3) contrast(1.05)`;$("whoImage").style.transform=`scale(${1.04+whoBlur/225})`;if(!silent)$("whoMessage").textContent="✨ Photo un peu moins floue";saveWho()}
$("whoFile").addEventListener("change",(e)=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=(ev)=>{$("whoImage").src=ev.target.result;$("whoImage").style.display="block";$("whoPlaceholder").style.display="none";localStorage.setItem("malou_who_img",ev.target.result)};r.readAsDataURL(f)});
$("whoGrid").addEventListener("change",()=>{buildWhoGrid();saveWho()});$("whoGoal").addEventListener("input",updateWhoScore);$("whoAnswer").addEventListener("input",()=>{$("secretAnswer").textContent=$("whoAnswer").value||"Réponse masquée";saveWho()});$("toggleAnswer").addEventListener("click",()=>{$("secretAnswer").classList.toggle("visible")});$("showClue").addEventListener("click",()=>{$("whoClue").textContent="💡 Indice : "+($("clueInput").value||"pas encore dévoilé");saveWho()});$("whoAdd").addEventListener("click",()=>{whoSubs++;revealWhoRandom();if(whoSubs%2===0)lessWhoBlur(true);updateWhoScore();if(whoSubs>=(parseInt($("whoGoal").value,10)||1)){$("whoMessage").textContent="🎉 OBJECTIF ATTEINT !!!";confetti()}});$("whoReveal").addEventListener("click",revealWhoRandom);$("lessBlur").addEventListener("click",()=>lessWhoBlur(false));$("whoReset").addEventListener("click",()=>{if(!confirm("Réinitialiser le Qui suis-je ?"))return;whoSubs=0;whoBlur=18;$("whoClue").textContent="💡 Indice : pas encore dévoilé";$("whoMessage").textContent="Partie réinitialisée 💖";$("whoImage").style.filter=`blur(${whoBlur}px) saturate(1.3) contrast(1.05)`;$("whoImage").style.transform="scale(1.12)";buildWhoGrid();updateWhoScore()});

/* TOUCHE COULE */
let shipPlacement=true,shipSunk=0;
function buildShipBoard(){const n=parseInt($("shipSize").value,10);const board=$("shipBoard");board.style.gridTemplateColumns=`repeat(${n},1fr)`;board.innerHTML="";for(let i=0;i<n*n;i++){const b=document.createElement("button");b.className="ship-cell";b.dataset.state="empty";b.addEventListener("click",()=>clickShip(b));board.appendChild(b)}shipPlacement=true;shipSunk=0;updateShipScore();$("shipMessage").textContent="Place tes bateaux en secret 👀"}
function clickShip(c){if(shipPlacement){c.classList.toggle("boat");c.dataset.state=c.classList.contains("boat")?"boat":"empty";return}if(c.classList.contains("miss")||c.classList.contains("hit")||c.classList.contains("sunk"))return;if(c.dataset.state==="boat"){c.classList.add("hit");c.textContent="💥";$("shipMessage").textContent="💥 TOUCHÉ !";if(confirm("Le bateau est-il coulé ?")){c.classList.remove("hit");c.classList.add("sunk");c.textContent="🚢";shipSunk++;updateShipScore();$("shipMessage").textContent="🎉 BATEAU COULÉ = 10 € !";confetti()}}else{c.classList.add("miss");c.textContent="💦";$("shipMessage").textContent="💦 À L’EAU"}}
function updateShipScore(){$("shipSunk").textContent=shipSunk;$("shipMoney").textContent=shipSunk*10}
$("shipStart").addEventListener("click",()=>{shipPlacement=false;document.querySelectorAll(".ship-cell.boat").forEach(c=>{c.classList.remove("boat");c.textContent=""});$("shipMessage").textContent="🎯 Partie lancée !"});$("shipMode").addEventListener("click",()=>{shipPlacement=true;document.querySelectorAll(".ship-cell").forEach(c=>{if(c.dataset.state==="boat"&&!c.classList.contains("hit")&&!c.classList.contains("sunk"))c.classList.add("boat")});$("shipMessage").textContent="Mode placement secret activé 👀"});$("shipSize").addEventListener("change",buildShipBoard);$("shipReset").addEventListener("click",()=>{if(confirm("Réinitialiser Touché Coulé ?"))buildShipBoard()});

/* BINGO */
const defaultTasks=["3 recos prises dans la journée","2 abos dans une démo groupée","Faire une blague dans un call","6 abos dans la journée","2 abos recos","Une objection micro pas de besoin déjouée","8 abos dans la journée","1 ami ajouté via le lien du jeune diplômé","3 RDV calés en moins d’1h","1 reco transformée en abo","Un vocal envoyé à un prospect","Relancer 10 ghosts","Faire +1 dans le thread","Un prospect qui dit merci","1 démo groupée lancée","1 objection comptable déjouée","1 abo après no-show","Faire rire le channel","5 appels d’affilée","1 école complétée","1 prospect rappelé dans la journée","1 screen victoire partagé","2 RDV pris via reco","1 abo en moins de 10 min","Finir une ligne de relance"];
$("bingoTasks").value=defaultTasks.join("\n");
function bingoKey(){return "malou_bingo_"+(($("bingoPlayer").value||"joueur").trim().toLowerCase().replaceAll(" ","_"))}
function shuffle(arr){return [...arr].sort(()=>Math.random()-0.5)}
function saveBingo(){const cells=[...document.querySelectorAll(".bingo-cell")].map(c=>({t:c.dataset.text,checked:c.classList.contains("checked")}));const data={player:$("bingoPlayer").value,size:$("bingoSize").value,reward:$("bingoReward").value,tasks:$("bingoTasks").value,cells};localStorage.setItem(bingoKey(),JSON.stringify(data))}
function buildBingo(fromCells=null){const player=($("bingoPlayer").value||"Joueur").trim();$("bingoName").textContent=player;$("bingoRewardText").textContent=$("bingoReward").value||"Gain à définir";const size=parseInt($("bingoSize").value,10);const board=$("bingoBoard");board.style.gridTemplateColumns=`repeat(${size},1fr)`;board.innerHTML="";let cells=fromCells;if(!cells){const tasks=$("bingoTasks").value.split("\n").map(t=>t.trim()).filter(Boolean);cells=shuffle(tasks).slice(0,size*size).map(t=>({t,checked:false}))}cells.forEach(item=>{const c=document.createElement("button");c.className="bingo-cell";c.dataset.text=item.t;c.textContent=item.t;if(item.checked)c.classList.add("checked");c.addEventListener("click",()=>{c.classList.toggle("checked");checkBingo();saveBingo()});board.appendChild(c)});$("bingoMessage").textContent="Clique sur les cases validées ✅";checkBingo();saveBingo()}
function checkBingo(){document.querySelectorAll(".bingo-cell").forEach(c=>c.classList.remove("win"));const size=parseInt($("bingoSize").value,10);const cells=[...document.querySelectorAll(".bingo-cell")];if(cells.length!==size*size)return false;const lines=[];for(let r=0;r<size;r++)lines.push([...Array(size)].map((_,i)=>r*size+i));for(let col=0;col<size;col++)lines.push([...Array(size)].map((_,i)=>i*size+col));lines.push([...Array(size)].map((_,i)=>i*size+i));lines.push([...Array(size)].map((_,i)=>i*size+(size-1-i)));for(const line of lines){if(line.every(i=>cells[i].classList.contains("checked"))){line.forEach(i=>cells[i].classList.add("win"));$("bingoMessage").textContent="🎉 BINGOOOOOO !!!";confetti();return true}}return false}
function loadBingo(){const key=bingoKey();const saved=localStorage.getItem(key);if(saved){try{const d=JSON.parse(saved);$("bingoSize").value=d.size||4;$("bingoReward").value=d.reward||"50 € pour le premier Bingo";$("bingoTasks").value=d.tasks||defaultTasks.join("\n");buildBingo(d.cells);return}catch(e){}}buildBingo()}
$("bingoGenerate").addEventListener("click",()=>buildBingo());$("bingoShuffle").addEventListener("click",()=>buildBingo());$("bingoReset").addEventListener("click",()=>{if(confirm("Réinitialiser le bingo de ce joueur ?")){localStorage.removeItem(bingoKey());buildBingo()}});$("bingoPlayer").addEventListener("change",loadBingo);$("bingoSize").addEventListener("change",()=>buildBingo());$("bingoReward").addEventListener("input",()=>{$("bingoRewardText").textContent=$("bingoReward").value;saveBingo()});$("bingoCopy").addEventListener("click",async()=>{const url=new URL(window.location.href);url.searchParams.set("player",$("bingoPlayer").value||"joueur");try{await navigator.clipboard.writeText(url.toString());$("bingoMessage").textContent="Lien copié 💜"}catch(e){$("bingoMessage").textContent="Copie ce lien : "+url.toString()}});

function loadWho(){buildWhoGrid();const img=localStorage.getItem("malou_who_img");if(img){$("whoImage").src=img;$("whoImage").style.display="block";$("whoPlaceholder").style.display="none"}const saved=localStorage.getItem("malou_who");if(saved){try{const d=JSON.parse(saved);whoSubs=d.subs||0;whoBlur=d.blur??18;$("whoGoal").value=d.goal||37;$("whoGrid").value=d.grid||10;$("whoAnswer").value=d.answer||"";$("secretAnswer").textContent=d.answer||"Réponse masquée";$("whoClue").textContent=d.clue||"💡 Indice : pas encore dévoilé";buildWhoGrid();[...document.querySelectorAll("#whoTiles .tile")].forEach((t,i)=>{if(d.hidden&&d.hidden[i])t.classList.add("hidden-tile")});$("whoImage").style.filter=`blur(${whoBlur}px) saturate(1.3) contrast(1.05)`;$("whoImage").style.transform=`scale(${1.04+whoBlur/225})`}catch(e){}}updateWhoScore()}
const params=new URLSearchParams(location.search);if(params.get("player"))$("bingoPlayer").value=params.get("player");
loadWho();buildShipBoard();buildBingo();